### ISSUE TITLE
File "GeneratedImages/image.jpeg" does not exist.

### ISSUE THREAD

**Issue by kiyohken2000** [andrei-zgirvaci/expo-stable-diffusion#3]
Thanks for your great work, it is much appreciated.

I am using expo-dev-client.  I have build a develop client for the simulator. I imitated your example.
After `await ExpoStableDiffusion.loadModel(MODEL_PATH)` followed by `await ExpoStableDiffusion.generateImage()`, after a few minutes "File "GeneratedImages/image .jpeg" does not exist" error.

What is wrong?

[Here is my code](https://github.com/kiyohken2000/stable-diffusion-app/blob/main/src/scenes/home/Home.js)

**Comment by andrei-zgirvaci** [comment]
Hi, thanks for opening the issue!

The error was happening due to a bug in how the path was parsed in Swift.

It should be fixed now in `0.1.2`. Please update and let me know if it works!

**Comment by kiyohken2000** [comment]
Thank you. I tried it in the simulator and it worked.

**Comment by andrei-zgirvaci** [comment]
Nice, happy to hear that!
