### ISSUE TITLE
Does this work in Expo Go?

### ISSUE THREAD

**Issue by JustJoostNL** [andrei-zgirvaci/expo-stable-diffusion#5]
Hey, first, great work on your module! I like it!

Can I use this module in Expo Go, or do I need an development build?

**Comment by andrei-zgirvaci** [comment]
Hi, unfortunately, you can't use `expo-stable-diffusion` in **Expo Go**, you will have to use a [Development Build](https://docs.expo.dev/develop/development-builds/introduction) or build it locally using Xcode!

And thanks for asking, I have added this note at the top of the README now! :)
